CREATE TABLE IF NOT EXISTS "schema_migrations" ("version" INTEGER PRIMARY KEY, "inserted_at" TEXT);
CREATE TABLE IF NOT EXISTS "tasks" ("id" TEXT PRIMARY KEY, "title" TEXT NOT NULL, "description" TEXT NOT NULL, "created_at" TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_att" TEXT NULL);
INSERT INTO schema_migrations VALUES(20250731220009,'2025-08-01T22:44:31');
